language: node_js
node_js: '6.10'
sudo: false
services:
  - redis-server
branches:
  only: master
before_deploy:
  - mkdir _build_to_deploy
  - rm -rf node_modules && npm i --production && zip -r _build_to_deploy/udsmider.zip index.js package.json node_modules src
deploy:
  - provider: s3
    bucket: cq-os-us-east-1
    local-dir: _build_to_deploy
    upload-dir: udsmider
    on:
      repo: cquotient/udsmider
      branch: master
    skip_cleanup: true
  - provider: s3
    bucket: cq-os-us-west-2
    local-dir: _build_to_deploy
    upload-dir: udsmider
    on:
      repo: cquotient/udsmider
      branch: master
    skip_cleanup: true
  - provider: s3
    bucket: cq-os-eu-west-1
    local-dir: _build_to_deploy
    upload-dir: udsmider
    on:
      repo: cquotient/udsmider
      branch: master
    skip_cleanup: true
  - provider: s3
    bucket: cq-os-ap-southeast-1
    local-dir: _build_to_deploy
    upload-dir: udsmider
    on:
      repo: cquotient/udsmider
      branch: master
    skip_cleanup: true
