version: 0.2

phases: 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - docker run -d -p 6379:6379 --name redis redis:5.0.0-alpine
      - mkdir ~/.ssh || echo "SSH dir already exists"
      - aws s3 cp s3://cq-aws-builds/ssh/codebuild_rsa.enc .
      - aws kms decrypt  --region "us-east-1"  --ciphertext-blob "fileb://codebuild_rsa.enc" --output text --query Plaintext | base64 --decode > ~/.ssh/codebuild_rsa
      - chmod 500 ~/.ssh/codebuild_rsa
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - aws s3 cp s3://cq-aws-builds/ssh/ssh_config ~/.ssh/config 
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - npm test
  post_build:
    commands:
      - echo Entered the post_build phase...
      - mkdir -p _build_to_deploy
      - rm -rf node_modules
      - npm i --production
      - zip -r _build_to_deploy/udsmider.zip index.js package.json node_modules src
artifacts:
  files:
    - _build_to_deploy/udsmider.zip
  secondary-artifacts:
    usw2:
      files:
        - _build_to_deploy/udsmider.zip
    euw1:
      files:
        - _build_to_deploy/udsmider.zip
    apse1:
      files:
        - _build_to_deploy/udsmider.zip